from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from mei.domain.imagery.models import ImageEvidence
from mei.shared.enums import VerificationStatus


class ImageryRepository:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get(self, image_id: UUID) -> ImageEvidence | None:
        return await self._session.get(ImageEvidence, image_id)

    async def get_by_content_hash(self, content_hash: str) -> ImageEvidence | None:
        result = await self._session.execute(
            select(ImageEvidence).where(ImageEvidence.content_hash == content_hash)
        )
        return result.scalars().first()

    async def list_images(
        self,
        *,
        source_id: UUID | None = None,
        verification_status: VerificationStatus | None = None,
        since: datetime | None = None,
        until: datetime | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[ImageEvidence]:
        stmt = select(ImageEvidence).order_by(ImageEvidence.retrieved_at.desc())
        if source_id is not None:
            stmt = stmt.where(ImageEvidence.source_id == source_id)
        if verification_status is not None:
            stmt = stmt.where(ImageEvidence.verification_status == verification_status)
        if since is not None:
            stmt = stmt.where(ImageEvidence.retrieved_at >= since)
        if until is not None:
            stmt = stmt.where(ImageEvidence.retrieved_at <= until)
        stmt = stmt.limit(limit).offset(offset)
        result = await self._session.execute(stmt)
        return list(result.scalars())

    async def create(
        self,
        *,
        image_id: UUID,
        source_id: UUID | None,
        document_id: UUID | None,
        object_key: str,
        content_hash: str,
        content_type: str,
        captured_at: datetime | None,
        retrieved_at: datetime,
        latitude: float | None,
        longitude: float | None,
        location_precision: str | None,
        caption: str | None,
        submitted_by_type: str,
        submitted_by_id: str | None,
    ) -> ImageEvidence:
        """`image_id` is generated by the caller (`ImageryIngestionService`)
        before this call, not left to the model's `default=uuid7`: the raw
        bytes are archived to object storage under a key that embeds this
        same id, and that has to happen before the row exists so a
        duplicate-content submission (caught by `content_hash` before this
        method is ever called) never leaves an orphaned object behind."""
        image = ImageEvidence(
            id=image_id,
            source_id=source_id,
            document_id=document_id,
            object_key=object_key,
            content_hash=content_hash,
            content_type=content_type,
            captured_at=captured_at,
            retrieved_at=retrieved_at,
            latitude=latitude,
            longitude=longitude,
            location_precision=location_precision,
            caption=caption,
            verification_status=VerificationStatus.UNREVIEWED,
            submitted_by_type=submitted_by_type,
            submitted_by_id=submitted_by_id,
        )
        self._session.add(image)
        await self._session.flush()
        return image

    async def set_analysis(
        self,
        image: ImageEvidence,
        *,
        analysis_json: dict[str, object],
        confidence: float | None,
        verification_status: VerificationStatus,
    ) -> ImageEvidence:
        image.analysis_json = analysis_json
        image.confidence = confidence
        image.verification_status = verification_status
        await self._session.flush()
        return image


__all__ = ["ImageryRepository"]
